### PR TITLE
WIP: Add CStack for 14.04

### PR DESCRIPTION
**Pull request by steffendsommer**
Please do not merge yet - we just want to see if this will build for 14.04 before adding it to the others.

### CODE REVIEW

**Comment by joscdk** [comment]
@steffendsommer should we try to build it on APT?

**Comment by steffendsommer** [comment]
@joscdk yes let's try that

**Comment by joscdk** [comment]
@vapor-ci-robot /approved

**Comment by joscdk** [comment]
@steffendsommer whoops, need to be `build.yaml` not `build.yml` :D

**Comment by BrettRToomey** [comment]
rip

**Comment by BrettRToomey** [comment]
Let's try again @joscdk

**Comment by joscdk** [comment]
@BrettRToomey @steffendsommer i can at least install it on 14.04 now .. 

Just saw you need to have the .sh as an executable when pushing, i will fix that, but for now just do:

```
chmod +x build.sh
```

When pushing to other distros :)

Can you test the cstack package work, on 14.04 simply do:
```
apt-get update
apt-get install cstack
```

**Comment by steffendsommer** [comment]
@joscdk can you approve again? I think we're there now.

**Comment by joscdk** [comment]
@steffendsommer done :)

**Comment by steffendsommer** [comment]
@joscdk I tested with 14.04 and everything worked 👍  I've now added it for each Linux version - it should be good to merge if it builds now. Thanks a lot for helping out.

**Pull request merged**
